apiVersion: crd.harborsync.k8s.io/v1
kind: HarborSyncConfig
metadata:
  name: harborsyncconfig-sample
spec:
  projectSelector:
  # 1:1 mapping between project & namespace
  - type: Regex
    name: team-(foo|bar|baz|bang)
    robotAccountSuffix: k8s-robot
    mapping:
    - type: Translate
      namespace: team-$1 # references harbor project name from above: team-foo, team-bar, ...
      secret: $1-pull-secret # foo-pull-secret, bar-pull-secret, ...
  # 1:n mapping
  # all team-* namespaces should have a platform/operations pull secret
  - type: Regex
    name: (platform|operations)-team
    robotAccountSuffix: k8s-robot
    mapping:
    - type: Match  # match namespaces using regex below
      namespace: team-.*
      secret: $1-pull-secret # platform-pull-secret, operations-pull-secret
    - type: Match
      namespace: kube-system
      secret: $1-pull-secret
