name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Install kubebuilder
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)
        curl -sL https://go.kubebuilder.io/dl/2.0.0/${os}/${arch} | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.0.0_${os}_${arch} /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
    - name: Install make
      run: sudo apt-get install -y make

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test
